version: "3.2"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  servidor:
    container_name: alexa_lol_league
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../rtsp-conversor/config.json:/config/config.json
    ports:
      - "8080:8080"

volumes:
  db-data:
    driver: local